
/**
 * Copyright (C) <2020>  <name of Samuel Amaro>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package view;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author SAMUE
 */
public class ViewLicence extends javax.swing.JFrame {

    /**
     * Creates new form ViewLicence
     */
    public ViewLicence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteinerAgrupaComponentes = new javax.swing.JPanel();
        lblHeaderMensage = new javax.swing.JLabel();
        abrirLinkLicenca = new javax.swing.JButton();
        btnJaConheceLicenca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        lblHeaderMensage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHeaderMensage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderMensage.setText("LICENÇA PUBLICA GERAL - GNU");

        abrirLinkLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_icones/iconfinder_licence_49373.png"))); // NOI18N
        abrirLinkLicenca.setText("Abrir Licença");
        abrirLinkLicenca.setPreferredSize(new java.awt.Dimension(93, 32));
        abrirLinkLicenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abrirLinkLicencaMouseEntered(evt);
            }
        });
        abrirLinkLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirLinkLicencaActionPerformed(evt);
            }
        });

        btnJaConheceLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_icones/iconfinder_check-mark-80px_510930.png"))); // NOI18N
        btnJaConheceLicenca.setText("Ja Conheço");
        btnJaConheceLicenca.setPreferredSize(new java.awt.Dimension(89, 32));
        btnJaConheceLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJaConheceLicencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conteinerAgrupaComponentesLayout = new javax.swing.GroupLayout(conteinerAgrupaComponentes);
        conteinerAgrupaComponentes.setLayout(conteinerAgrupaComponentesLayout);
        conteinerAgrupaComponentesLayout.setHorizontalGroup(
            conteinerAgrupaComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteinerAgrupaComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conteinerAgrupaComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeaderMensage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(conteinerAgrupaComponentesLayout.createSequentialGroup()
                        .addComponent(btnJaConheceLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(abrirLinkLicenca, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        conteinerAgrupaComponentesLayout.setVerticalGroup(
            conteinerAgrupaComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteinerAgrupaComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeaderMensage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(conteinerAgrupaComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirLinkLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJaConheceLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteinerAgrupaComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteinerAgrupaComponentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(296, 100));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ao clicar na opção ja conhece ja sai da view de informação de licença;
     * @param evt 
     */
    private void btnJaConheceLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJaConheceLicencaActionPerformed
        dispose();
    }//GEN-LAST:event_btnJaConheceLicencaActionPerformed

    /*
    Mouse passou por cima do botão ou estar no botão encima do quadro do botão, vai abrir o link de texto da licença;
    */
    private void abrirLinkLicencaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirLinkLicencaMouseEntered
        
 
        
    }//GEN-LAST:event_abrirLinkLicencaMouseEntered

    /**
     * Ao cliar nesse botão vai abrir um texto, onde o usuairo poderar ler o texto da licença;
     * @param evt 
     */
    private void abrirLinkLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirLinkLicencaActionPerformed
        try {
              URI link = new URI("https://www.gnu.org/licenses/gpl-3.0.pt-br.html");  
             try {
                 Desktop.getDesktop().browse(link);
            } catch (IOException e) {
                    System.out.println("Erro ao abrir navegador" + e);
            }    
        } catch (URISyntaxException e) {
               System.out.println("ERRO AO ABRIR LINK " + e);
        }
    }//GEN-LAST:event_abrirLinkLicencaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirLinkLicenca;
    private javax.swing.JButton btnJaConheceLicenca;
    private javax.swing.JPanel conteinerAgrupaComponentes;
    private javax.swing.JLabel lblHeaderMensage;
    // End of variables declaration//GEN-END:variables
}
